name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/buildWin

    - name: Install vcpkg
      run: |
        mkdir ${{github.workspace}}/external
        git clone https://github.com/Microsoft/vcpkg.git ${{github.workspace}}/external/vcpkg
        ${{github.workspace}}/external/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      shell: pwsh
      run: cmake "${{github.workspace}}" -B "${{github.workspace}}/buildWin" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      shell: pwsh
      run: cmake --build "${{github.workspace}}/buildWin" --config ${{ matrix.build_type }}

    - name: Test
      shell: pwsh
      working-directory: ${{github.workspace}}/buildWin
      run: ctest -C ${{ matrix.build_type }}
