name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/buildAppleSil

    - name: Install vcpkg
      run: |
        mkdir ${{github.workspace}}/external
        git clone https://github.com/Microsoft/vcpkg.git ${{github.workspace}}/external/vcpkg
        ${{github.workspace}}/external/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      shell: bash
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/buildAppleSil -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_OSX_ARCHITECTURES=arm64

    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/buildAppleSil --config ${{ matrix.build_type }}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/buildAppleSil
      run: ctest -C ${{ matrix.build_type }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{github.workspace}}/buildAppleSil/**
