name: Documentation

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        name: Build and publish documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - name: Install Docs
              run: |
                  sudo apt-get install doxygen
                  pip install jinja2 Pygments
            - name: prepare
              run: |
                  make prepare
            - name: configure
              run: |
                  cmake -H. -Bdocs -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
            - name: building
              run: |
                  cmake --build ${{github.workspace}}/docs --config ${{github.workspace}}/docs --target ${{github.workspace}}/docs -j4

            - name: archive artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: docs
                    path: ${{github.workspace}}/docs
