name: C++ CI

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                build_type: [Release]

        steps:
            - uses: actions/checkout@v2

            - name: Create Build Environment
              run: cmake -E make_directory ${{github.workspace}}/BuildMacOS

            - name: Install vcpkg
              run: |
                  mkdir ${{github.workspace}}/external
                  git clone https://github.com/Microsoft/vcpkg.git ${{github.workspace}}/external/vcpkg
                  ${{github.workspace}}/external/vcpkg/bootstrap-vcpkg.sh

            - name: Configure CMake
              shell: bash
              run: cmake ${{github.workspace}} -B ${{github.workspace}}/BuildMacOS -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_OSX_ARCHITECTURES=arm64

            - name: Build
              shell: bash
              run: cmake --build ${{github.workspace}}/BuildMacOS --config ${{ matrix.build_type }}

            - name: Test
              shell: bash
              working-directory: ${{github.workspace}}/BuildMacOS
              run: ctest -C ${{ matrix.build_type }}

            - name: Archive production artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build-artifacts
                  path: ${{github.workspace}}/BuildMacOS/**
