name: C++ CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/windowsBuild

    - name: Install vcpkg
      run: |
        mkdir ${{github.workspace}}/external
        git clone https://github.com/Microsoft/vcpkg.git ${{github.workspace}}/external/vcpkg
        ${{github.workspace}}/external/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      shell: pwsh
      run: cmake "${{github.workspace}}" -B "${{github.workspace}}/windowsBuild" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      shell: pwsh
      run: cmake --build "${{github.workspace}}/windowsBuild" --config ${{ matrix.build_type }}

    - name: Test
      shell: pwsh
      working-directory: ${{github.workspace}}/windowsBuild
      run: ctest -C ${{ matrix.build_type }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{github.workspace}}/windowsBuild/**
